---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: csi-metrics
  namespace: system-rook-ceph
  labels:
    team: rook
spec:
  namespaceSelector:
    matchNames:
    - system-rook-ceph
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: system-rook-ceph
  endpoints:
  - port: csi-http-metrics
    path: /metrics
    interval: 5s
