---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openhab-config-v1
  namespace: home-automation
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: rook-ceph-block
