---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openhab
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.itstoni.com/
      chart: openhab
      version: 1.0.3
      sourceRef:
        kind: HelmRepository
        name: kilip-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: openhab/openhab
      tag: 3.1.0
    env:
      TZ: "Europe/Stockholm"
    envFrom:
      - secretRef:
          name: openhab
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
        - host: openhab.cluster.stromberg.internal
          paths:
          - path: /
            pathType: Prefix
        tls:
          - hosts:
              - openhab.cluster.stromberg.internal
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    addons:
      codeserver:
        enabled: false
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: 3.11.1
        workingDir: "/config"
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
          - host: hass-config.cluster.stromberg.internal
            paths:
            - path: /
              pathType: Prefix
          tls:
            - hosts:
                - hass-config.cluster.stromberg.internal
        volumeMounts:
          - name: config
            mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
