---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: nfs
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    type: FileStore
    fileStore:
      claimName: nfs-nas-k10
      path: k10
    credential:
      secretType: ""
      secret:
        apiVersion: ""
        kind: ""
        name: ""
        namespace: ""
