---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kasten-nfs-nas-k10
spec:
  storageClassName: kasten-nas-k10
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.10.10.110
    path: /mnt/Backup/Kubernetes/Kasten
  mountOptions:
    - nfsvers=4.1
    - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nas-k10
  namespace: kasten-io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kasten-nas-k10
  resources:
    requests:
      storage: 1Mi
