---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: system-rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v16.2.5
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  skipUpgradeChecks: false
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  removeOSDsIfOutAndSafeToRemove: false
  mon:
    count: 3
    allowMultiplePerNode: false
  placement:
    all:
      tolerations:
      - effect: "NoExecute"
        operator: "Exists"
      - effect: "NoSchedule"
        operator: "Exists"
  monitoring:
    enabled: false
    rulesNamespace: rook-ceph
  network:
  crashCollector:
    disable: false
  cleanupPolicy:
    confirmation: ""
    sanitizeDisks:
      method: quick
      dataSource: zero
      iteration: 1
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
    port: 7000
    ssl: false
  disruptionManagement:
    managePodBudgets: false
    osdMaintenanceTimeout: 30
    manageMachineDisruptionBudgets: false
    machineDisruptionBudgetNamespace: openshift-machine-api
  resources:
    mon:
      requests:
        cpu: 35m
        memory: 800Mi
      limits:
        memory: 1536Mi
    osd:
      requests:
        cpu: "35m"
        memory: "2048Mi"
      limits:
        memory: "4096Mi"
  storage:
    useAllNodes: true
    useAllDevices: true
    config:
      osdsPerDevice: "1"
    
