# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:zNP62XYBdBNl,iv:Zqe6WdVmK61aEYmrE8oA9lXttd50uXEs4E3X8X4Pq2U=,tag:iiYvuBP4zOq5Hbu9v6k+PA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-22T14:28:52Z"
    mac: ENC[AES256_GCM,data:VgG8cOqWIfWEpfY8DwQBvMHj43dgLUsJd/Ozj9WfcwWUfEvpyJv+1ionXS9nhQY39CbwBsjxCaVgyAdRCpsspvw4VwVL8c941bDNb75W5dxtd7P6F2Lp7yDZ+DZcnhd+N1k110k7q4WmdSOAbbJhh8bQjgOgg+f5kNG3qJUqGvE=,iv:f+N3U4s/1v7RgXK09Ve+m/0vdw2rJuImTOz3A6uSbXI=,tag:adZ0wMIDYpoe2wMYevaqqg==,type:str]
    pgp:
        - created_at: "2021-07-22T14:28:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyYJfj2+h3/bAQ/9GPGq9fkurvRj8G+UYEjXrSQdJHOPpVFoWN7DDmFKOq80
            N4fxRmSVA4112vHO4et8ZjYfGjWahi8aHCQcKPFQxDjPStVnwAYUt8kD4FVYvCjW
            7DSVCdDpcn3iCb3wsYCwY/y7Rrsfeg5YdUV31CNCRBeLbm7P6Qe00bGKGUm7L422
            4/LvBnh9IU46PJqVUnLFfHR2j3yVRVcPq85ZXBSbmYflg+RT5IlqZuH+sYCLSR6s
            qySAx1JdVX1Ul8r8X7d/O3GsIz5bj9b2QGG/SdV52cyDqu03fQLraRlGuVkkB5eU
            QVk4Y+ulajW/L5EfF5GgMqz2txWofeAoZhhO0CS/orjwVtw6MRzxN1KIqQ7ON0fX
            nOlKJxAzcaDYzjnJpb/RDiUoquMqLITO/pC1CggSZ/OP56obuLlBcfvhN7B+6qFJ
            uGCrT1sxAlIgp8y/isk7CJphlmYDzIDkiQVaC7mhrfjMN5eHe7uult47vcV3rLXQ
            br2NuDKLC8i7/Md5FE9rV0Ld7D3FFulg5MDSzePgOIGqtCIKNwHu7p78Z0YYR7GY
            t4MWQDCYt+yGNEHOgqmvNiLMjFA3B4K9zFND1ZA1N/k0+sxlsS8ZGX52+kg6BJ2X
            TC0pYLYTHsu1E06ZAI4D5eyPEFUJf4JfUZjAxmXnFeGeE0exBPnFFTsYOEg4v3bS
            XgHr/LcZOBaGnox0w+pBP9Doktnv8b7VJu6DlWhKSyNdjUQThTBOVVWrDmxlgThX
            v8IduJQvrN+wUdyr5poAm03N2nUaymgvEqDb8sg8CqzxS1wzssrnTZuAxw2qHdk=
            =sVHz
            -----END PGP MESSAGE-----
          fp: 86E4E1F7712D4E6E0182B36AB1DB4BECBD30350C
        - created_at: "2021-07-22T14:28:52Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4qMc0LBd4T4AQ//dU3yjQkO/Yqt1PDOsUI3fSISEYoJBTL2NPTlf0TJ6FEG
            oqVlycRZYZlAVFiXJgJ23SGP0zM14szft8O5xJV+BPBxOurQae9+NL94jzkW2o4z
            3onOIsQo9olJDymdtOh4wZzuFyA7iF9qjGPMIhMRTSz8EtXKb5tkSKmOx/NrzGQn
            S5giqT4bpb3QcHpPghsI736ysAC0XtQteWkrebPiLSmj6EyhVcl8KJi9hHL2VF0q
            pqq04ttS6Ke736hAmwbGxHCHrrJyiEVOxLy6ZJh1MNVHCOVSuScygaL/nQNSkgRl
            i91XSN1dUgJ+0dGcHWOzyXIA3mpCeskTJzZULyShvmwfyvIotkOXljipYkhvtdUS
            6/vdQCf+86lPLLlm9c/V2KyhZsE+iv9OfM+VIJyMp1F3sinbF7KZ+vzUd7JWx5bq
            kB2ITgJ+JOVaMasO3pxtbPH6DIlI+VCE5Izw/tuPXhg+pTa7zjvsuVu2SR4yz2ym
            FuoJa5fIWtCtEU1lmj7y08jjxdmF6pdlVEDJmtBY8gvU1wreemrvMUFWWYlqxfW5
            IIPUKFf20GFXFs0m0oyH1aevHIPLVcGhBcILStnMS5ZAhl0YUMTSntALcABa1Fih
            5WzglbYJwtwvk4RB9LySurei0X4Kcgoim9t0LAM04diDU4AFADjRTg+kRbIyJwTS
            XgHIQcECo2amv17hiIEWh8Z8XMPiqe8YJcw44Q1j2igfwXXqHrVHysQWcHFzHOA8
            Z97fAedGZtScCrASPAUh91S6vEJtMe2mYY2Unh5jNjmzqcMKOWvFdChfqTvNhlA=
            =07DM
            -----END PGP MESSAGE-----
          fp: 6EAFAF204759F3B9D6812CB7940F21E03D463B52
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
