apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- flux-system.yaml
- kasten-io.yaml
- kube-system.yaml
- metallb-system.yaml
- monitoring.yaml
- networking.yaml
- rook-ceph.yaml
